### ISSUE TITLE
Current Step Percentage Completion not working with 0.

### ISSUE THREAD

**Issue by JCUK89** [SFDC-Assets/DynamicFlowProgress#1]
Hi there,

Just wanted to feedback that the component displays incorrect output when the Current Step Percentage Completion field is set to 0 either directly or via a number variable. 

When the field is set to 0, the output component (Bar, Ring) outputs 100% instead of 0%.

When it is set to any other value, it functions correctly.

I hope this helps.

Thanks

Jan

**Comment by egyptguy** [comment]
Hi Jan - thanks for reporting!   Sorry you're having trouble with it.  I can't say I've been able to replicate the issue though - when I set Current Step Percentage Completion to 0, I see 0% in the ring and bar.  If you set the field to 0 on the first screen of the included sample flow and activate the new version, do you get a different result than this:

![image](https://user-images.githubusercontent.com/7809764/145226722-36867b26-b7f4-4a8f-b674-506750778d66.png)

**Comment by JCUK89** [comment]
Hi Mitch - thanks very much for the response.

When I followed your steps, I was able to see the same output - however, I tried setting the values to 0 in the second screen on both ring & path and ring outputs 20% instead of 0%, path outputs 0% only when the current stage is set to Step 1, If I set it to Step 2 it outputs 20% regardless the 0 override.

![Screenshot 2021-12-08 at 15 43 00](https://user-images.githubusercontent.com/95492181/145237955-0b4d00b3-c92e-4f6e-a94c-98201fe5a25d.png)

**Comment by egyptguy** [comment]
Hi Jan - Happy New Year!  Sorry, I'm not getting notifications of new messages for some strange reason.  I guess I have to report an issue with Issues :) I'm still unable to reproduce this, but I'll keep an eye out for odd behavior in the component.  Thanks again for your feedback (and your review)! - Mitch

**Comment by zjsaad** [comment]
Hello!  What a wonderful tool you've created.

I am playing around with it and found the same issue as JCUK89.

When I leave the Current Step Percentage Completion fields blank, it displays the progress indicator as 100, even if I have 4 different steps.  When I don't leave them blank but rather fill them each in with 0, 25, 50, 75, 100), it displays it properly.

For instance, when the field is left blank on the 4 screens, the first page looks ok, but when I click Next, the second screen shows the correct screen, but the progress indicator shows completed for all 4 stages.  Same goes for screens 3 and 4 as well.

I'm happy to provide screenshots if that's helpful.  Thanks so much!!
