### ISSUE TITLE
Last step in path marked as completed as soon as approached

### ISSUE THREAD

**Issue by oleg-mastriukov** [SFDC-Assets/DynamicFlowProgress#18]
In my flow, I have 4 active stages with the orders 10, 20, 30, and 40. As soon as the flow approaches the last step, it's marked as completed with the green checkmark.
I assume it should be marked blue until you complete it.
The condition when the flow is on the 3rd screen:
![image](https://github.com/SFDC-Assets/DynamicFlowProgress/assets/46223141/53f02e9b-ff12-4c86-bca1-cfbbe0d9e302)
The condition when the flow goes to the last stage:
![image](https://github.com/SFDC-Assets/DynamicFlowProgress/assets/46223141/d588afcc-d45e-4fa0-95a8-f1565cba5440)

The same thing is happening with the path in the sample flow from the repository:
![image](https://github.com/SFDC-Assets/DynamicFlowProgress/assets/46223141/7eea4240-7c4b-4e34-a119-4a5643850c17)

But the demo gif on the main page shows the last step in a proper blue state:
![image](https://github.com/SFDC-Assets/DynamicFlowProgress/assets/46223141/d63f569d-f91e-4043-8e76-9157a9ad284b)

Workarounds:
1. Create the 5th active stage which will never be assigned for the current stage, but in terms of user experience, it's not good to have an extra step in the indicator
2. In the dynamicFlowProgressLWC.js, add ```+1``` to this part:
```
            let isFinalStep = false;
            if(currentCount == countTotalSteps+1){
                isFinalStep = true;
            }
```

**Comment by egyptguy** [comment]
I'm closing out this issue, as the documentation indicates that this is actually the intended/desired functionality of the component.
