### ISSUE TITLE
Path is Linked which reloads the page and the flow

### ISSUE THREAD

**Issue by jkenzer** [SFDC-Assets/DynamicFlowProgress#5]
Is this the same code as [this package](https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3u00000Pt7yzEAB)?

If so, many thanks for the contribution to the community and for making it available. If not, then this may or may not be applicable to your code.

The path works great, but each stage in the path is hyperlinked. If a user clicks on the status, it reloads the page the flow is embedded in which starts my flow over again. 

![image](https://user-images.githubusercontent.com/643517/161871728-5d6b9403-773c-49bc-86a2-d88bdc49d042.png)

Would it be possible to not make these clickable or set to preventDefault on click?

**Comment by esnorris** [comment]
Encountering the same issue which will cause the flow's progress to be lost when the page is reloaded.

**Comment by egyptguy** [comment]
Hi @jkenzer - thanks for reporting this!  I've fixed this in an LWC version of the component that I'll be releasing shortly here (and on the AppExchange once the security review is complete).  Thanks for making this open source project better!  @esnorris thanks for confirming the problem, too!

**Comment by jverelst** [comment]
@egyptguy I was also running into this issue and happy to see that it is already fixed in the upcoming version! Thanks for actively maintaining this package! It saved me a lot of time, because I feared I had to build something myself.

Any idea yet when the new package is released? It's not necessary for me to wait for the Appexchange release, I can just install it by package id (and I am willing to also test it on our sandbox if you like)

**Comment by egyptguy** [comment]
A quick update:  I'm conducting final testing now for an LWC version of the component and hope to get it through the security review in the next week or two.

@jverelst apologies I can't release an updated package until it passes the security review, but if you're using the unmanaged package version you can make the fix by simply removing the <a> tags (and their end tags) from lines 219, 233, and 247 of the [component's markup](https://github.com/SFDC-Assets/DynamicFlowProgress/blob/main/force-app/main/default/aura/DynamicFlowProgress/DynamicFlowProgress.cmp), as they were unnecessary elements of the SLDS blueprint.

**Comment by jkenzer** [comment]
Thank you for the update. I appreciate it and your work on this project.

**Comment by egyptguy** [comment]
@jkenzer @jverelst @esnorris thank you for your feedback and patience.  v2.0 is now live and available as an upgrade!  It resolves this issue, although I will leave the issue open for a while longer in case there are lingering issues not caught during testing.  To try it out, I would recommend verifying in a sandbox prior to installing in production.

**Comment by jkenzer** [comment]
@egyptguy I just tested in Sandbox and pushed to production. Works perfect. Thanks!

**Comment by jverelst** [comment]
I've also tested it in a scratch org, and I do happen to see a difference in behaviour between the old component and the new LWC component. 

The difference is between the rendering of a path, when you are in the final step. So I was wondering if I want to show in my path that I am in the last step, but that stap hasn't yet completed, how do I do that with the new LWC component?

### Original (version 1.2)
![image](https://user-images.githubusercontent.com/1706949/192256141-c8e3eb27-6ef9-4669-8dc0-61d9589ed77f.png)

renders like:

![image](https://user-images.githubusercontent.com/1706949/192256219-73ad7f57-dedc-4ff4-99d5-e237c699610a.png)

(to get the last step to be fully green, you can set the percentage to '100' and use a step name that isn't in the list of steps, that was a workaround that I was using).

### LWC version (2.0)

![image](https://user-images.githubusercontent.com/1706949/192256390-e8caa329-f34a-48df-94e1-0d30f94950dc.png)

renders like:
![image](https://user-images.githubusercontent.com/1706949/192256332-c9171ba2-fa80-4c77-9477-246f31cb8141.png)
